name: FutStats Daily Cron
run: |
          echo "DATABASE: $DATABASE_URL"
          echo "BASE: $THESPORTSDB_BASE_URL"
          echo "APIKEY: ${#THESPORTSDB_API_KEY} chars"

on:
  schedule:
    - cron: "0 6 * * *"  # 03:00 no Brasil
  workflow_dispatch:

jobs:
  run-routine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd futstats
          pip install -r requirements.txt

      - name: Run routine
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          THESPORTSDB_API_KEY: ${{ secrets.THESPORTSDB_API_KEY }}
          THESPORTSDB_BASE_URL: ${{ secrets.THESPORTSDB_BASE_URL }}
        run: |
          cd futstats
          python manage.py rotina_diaria
